# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# 1: insidious 2: orphan 3: Exorcist 4: bird 5: ring
#you have already seeded this but in case you need to drop and restart!

Movie.create(:name => "Insidious", :description => "Directed by the infamous Christina Stewart, this psychological horror/thriller is a must-see. Full of plot-twists and truly 'mental' layers, journalist Nora meets the patients at the Pine asylum.")
Movie.create(:name => "Orphan", :description => "A husband and wife who recently lost their baby adopt a 9-year-old girl who is not nearly as innocent as she claims to be.")
Movie.create(:name => "The Exorcist", :description => "When a teenage girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.")
Movie.create(:name => "The Birds", :description => "Birds of all kinds suddenly begin to attack people in a small down in increasing numbers and with increasing viciousness.")
Movie.create(:name => "The Ring", :description => "A young journalist must investigate a mysterious videotape which seems to cause the death of anyone within a week of viewing it.")

Showing.create(:day => "Tuesday, July 9", :hour => "12:00 pm", :movie_id => 1)
Showing.create(:day => "Tuesday, July 9", :hour => "5:00 pm", :movie_id => 1)
Showing.create(:day => "Tuesday, July 9", :hour => "7:30 pm", :movie_id => 1)
Showing.create(:day => "Tuesday, July 9", :hour => "12:00 am", :movie_id => 1)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 pm", :movie_id => 1)
Showing.create(:day => "Wednesday, July 10", :hour => "5:00 pm", :movie_id => 1)
Showing.create(:day => "Wednesday, July 10", :hour => "7:30 pm", :movie_id => 1)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 am", :movie_id => 1)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 pm", :movie_id => 1)
Showing.create(:day => "Thursday, July 11", :hour => "5:00 pm", :movie_id => 1)
Showing.create(:day => "Thursday, July 11", :hour => "7:30 pm", :movie_id => 1)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 am", :movie_id => 1)
Showing.create(:day => "Friday, July 12", :hour => "12:00 pm", :movie_id => 1)
Showing.create(:day => "Friday, July 12", :hour => "5:00 pm", :movie_id => 1)
Showing.create(:day => "Friday, July 12", :hour => "7:30 pm", :movie_id => 1)
Showing.create(:day => "Friday, July 12", :hour => "12:00 am", :movie_id => 1)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 pm", :movie_id => 1)
Showing.create(:day => "Saturday, July 13", :hour => "5:00 pm", :movie_id => 1)
Showing.create(:day => "Saturday, July 13", :hour => "7:30 pm", :movie_id => 1)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 am", :movie_id => 1)

Showing.create(:day => "Tuesday, July 9", :hour => "12:00 pm", :movie_id => 2)
Showing.create(:day => "Tuesday, July 9", :hour => "5:00 pm", :movie_id => 2)
Showing.create(:day => "Tuesday, July 9", :hour => "7:30 pm", :movie_id => 2)
Showing.create(:day => "Tuesday, July 9", :hour => "12:00 am", :movie_id => 2)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 pm", :movie_id => 2)
Showing.create(:day => "Wednesday, July 10", :hour => "5:00 pm", :movie_id => 2)
Showing.create(:day => "Wednesday, July 10", :hour => "7:30 pm", :movie_id => 2)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 am", :movie_id => 2)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 pm", :movie_id => 2)
Showing.create(:day => "Thursday, July 11", :hour => "5:00 pm", :movie_id => 2)
Showing.create(:day => "Thursday, July 11", :hour => "7:30 pm", :movie_id => 2)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 am", :movie_id => 2)
Showing.create(:day => "Friday, July 12", :hour => "12:00 pm", :movie_id => 2)
Showing.create(:day => "Friday, July 12", :hour => "5:00 pm", :movie_id => 2)
Showing.create(:day => "Friday, July 12", :hour => "7:30 pm", :movie_id => 2)
Showing.create(:day => "Friday, July 12", :hour => "12:00 am", :movie_id => 2)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 pm", :movie_id => 2)
Showing.create(:day => "Saturday, July 13", :hour => "5:00 pm", :movie_id => 2)
Showing.create(:day => "Saturday, July 13", :hour => "7:30 pm", :movie_id => 2)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 am", :movie_id => 2)

Showing.create(:day => "Tuesday, July 9", :hour => "12:00 pm", :movie_id => 3)
Showing.create(:day => "Tuesday, July 9", :hour => "5:00 pm", :movie_id => 3)
Showing.create(:day => "Tuesday, July 9", :hour => "7:30 pm", :movie_id => 3)
Showing.create(:day => "Tuesday, July 9", :hour => "12:00 am", :movie_id => 3)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 pm", :movie_id => 3)
Showing.create(:day => "Wednesday, July 10", :hour => "5:00 pm", :movie_id => 3)
Showing.create(:day => "Wednesday, July 10", :hour => "7:30 pm", :movie_id => 3)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 am", :movie_id => 3)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 pm", :movie_id => 3)
Showing.create(:day => "Thursday, July 11", :hour => "5:00 pm", :movie_id => 3)
Showing.create(:day => "Thursday, July 11", :hour => "7:30 pm", :movie_id => 3)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 am", :movie_id => 3)
Showing.create(:day => "Friday, July 12", :hour => "12:00 pm", :movie_id => 3)
Showing.create(:day => "Friday, July 12", :hour => "5:00 pm", :movie_id => 3)
Showing.create(:day => "Friday, July 12", :hour => "7:30 pm", :movie_id => 3)
Showing.create(:day => "Friday, July 12", :hour => "12:00 am", :movie_id => 3)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 pm", :movie_id => 3)
Showing.create(:day => "Saturday, July 13", :hour => "5:00 pm", :movie_id => 3)
Showing.create(:day => "Saturday, July 13", :hour => "7:30 pm", :movie_id => 3)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 am", :movie_id => 3)

Showing.create(:day => "Tuesday, July 9", :hour => "12:00 pm", :movie_id => 4)
Showing.create(:day => "Tuesday, July 9", :hour => "5:00 pm", :movie_id => 4)
Showing.create(:day => "Tuesday, July 9", :hour => "7:30 pm", :movie_id => 4)
Showing.create(:day => "Tuesday, July 9", :hour => "12:00 am", :movie_id => 4)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 pm", :movie_id => 4)
Showing.create(:day => "Wednesday, July 10", :hour => "5:00 pm", :movie_id => 4)
Showing.create(:day => "Wednesday, July 10", :hour => "7:30 pm", :movie_id => 4)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 am", :movie_id => 4)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 pm", :movie_id => 4)
Showing.create(:day => "Thursday, July 11", :hour => "5:00 pm", :movie_id => 4)
Showing.create(:day => "Thursday, July 11", :hour => "7:30 pm", :movie_id => 4)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 am", :movie_id => 4)
Showing.create(:day => "Friday, July 12", :hour => "12:00 pm", :movie_id => 4)
Showing.create(:day => "Friday, July 12", :hour => "5:00 pm", :movie_id => 4)
Showing.create(:day => "Friday, July 12", :hour => "7:30 pm", :movie_id => 4)
Showing.create(:day => "Friday, July 12", :hour => "12:00 am", :movie_id => 4)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 pm", :movie_id => 4)
Showing.create(:day => "Saturday, July 13", :hour => "5:00 pm", :movie_id => 4)
Showing.create(:day => "Saturday, July 13", :hour => "7:30 pm", :movie_id => 4)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 am", :movie_id => 4)

Showing.create(:day => "Tuesday, July 9", :hour => "12:00 pm", :movie_id => 5)
Showing.create(:day => "Tuesday, July 9", :hour => "5:00 pm", :movie_id => 5)
Showing.create(:day => "Tuesday, July 9", :hour => "7:30 pm", :movie_id => 5)
Showing.create(:day => "Tuesday, July 9", :hour => "12:00 am", :movie_id => 5)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 pm", :movie_id => 5)
Showing.create(:day => "Wednesday, July 10", :hour => "5:00 pm", :movie_id => 5)
Showing.create(:day => "Wednesday, July 10", :hour => "7:30 pm", :movie_id => 5)
Showing.create(:day => "Wednesday, July 10", :hour => "12:00 am", :movie_id => 5)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 pm", :movie_id => 5)
Showing.create(:day => "Thursday, July 11", :hour => "5:00 pm", :movie_id => 5)
Showing.create(:day => "Thursday, July 11", :hour => "7:30 pm", :movie_id => 5)
Showing.create(:day => "Thursday, July 11", :hour => "12:00 am", :movie_id => 5)
Showing.create(:day => "Friday, July 12", :hour => "12:00 pm", :movie_id => 5)
Showing.create(:day => "Friday, July 12", :hour => "5:00 pm", :movie_id => 5)
Showing.create(:day => "Friday, July 12", :hour => "7:30 pm", :movie_id => 5)
Showing.create(:day => "Friday, July 12", :hour => "12:00 am", :movie_id => 5)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 pm", :movie_id => 5)
Showing.create(:day => "Saturday, July 13", :hour => "5:00 pm", :movie_id => 5)
Showing.create(:day => "Saturday, July 13", :hour => "7:30 pm", :movie_id => 5)
Showing.create(:day => "Saturday, July 13", :hour => "12:00 am", :movie_id => 5)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 1)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 1)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 2)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 2)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 3)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 3)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 4)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 4)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 5)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 5)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 6)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 6)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 7)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 7)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 8)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 8)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 9)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 9)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 10)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 10)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 11)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 11)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 12)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 12)

Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => 13)
Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => 13)

for i in 14..100
	Ticket.create(:price => "$7.00", :seat_number => "A1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "A13", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "B13", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "C13", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "D13", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "E13", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F1", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F2", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F3", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F4", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F5", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F6", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F7", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F8", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F9", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F10", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F11", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F12", :showing_id => i)
	Ticket.create(:price => "$7.00", :seat_number => "F13", :showing_id => i)
end 


